name: compressed report
author: poyoho
description: compressed json file and comment in pull requests
branding:
  color: blue
  icon: code
inputs:
  token:
    description: The GitHub token used to create an authenticated client
    required: false
    default: ${{ github.token }}
  old-paths:
    description: old records path
    required: false
  new-paths:
    description: new records path
    required: false
  fields:
    description: extract fields
    required: false
runs:
  using: node16
  main: dist/index.js
